### ISSUE TITLE
Move to wagtail Github organisation

### ISSUE THREAD

**Issue by tomdyson** [leukeleu/wagtail-pg-search-backend#10]
We'd welcome this project in the wagtail Github organisation. If you agree, let me know if I can help with this.

https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

Thanks

Tom

**Comment by jaap3** [comment]
I'm in favour of this and I'd be happy to transfer this repo to the Wagtail organisation. There's one thing that needs to be arranged before we can do this; from the article you linked:

"The user transferring a repository must have owner or admin permissions in both organizations to complete a repository transfer."

I can add you to this repository as an admin, but you don't seem to be a member of the Wagtail organisation (or at least not a public member). Can you confirm you are in fact a member with the correct permissions? If not, please provide me with the GitHub username of a person who is.

I'd also like to add the correct people as maintainers to PyPI. Could you please provide a list of PyPI usernames that should be added to the package there?

**Comment by tomdyson** [comment]
Thanks @jaap3. Yes, I am an owner of the wagtail org. The two PyPI users are

- mattwestcott
- torchbox

**Comment by jaap3** [comment]
Thanks @tomdyson, you should have an invitation to become a member of this repository in your GitHub inbox. Once you accept it you should have sufficient rights to perform the move of this repository to the Wagtail organisation.

I've also added the PyPI users as package owners on PyPI.

**Comment by tomdyson** [comment]
Hi @jaap3, FYI I haven't received an invitation yet. Could you also try inviting Matt Westcott (@gasman)? Thanks!

**Comment by jaap3** [comment]
I've added @gasman as well, the invitation should be visible at https://github.com/leukeleu/wagtail-pg-search-backend/invitations

**Comment by 153957** [comment]
@tomdyson/@gasman
Can you also activate Travis for this repo under wagtail?
