### ISSUE TITLE
Integrate into wagtail

### ISSUE THREAD

**Issue by 153957** [leukeleu/wagtail-pg-search-backend#11]
There is already a PR which implements this repo as a contrib module in wagtail: wagtail/wagtail#3515

**Comment by BertrandBordage** [comment]
This pull request [has been merged](https://github.com/wagtail/wagtail/commit/e62d67bd730a1358124b821d291c272f9b955797), so this project will be available in Wagtail 1.10 as the `wagtail.contrib.postgres_search` module!

**Comment by jaap3** [comment]
Will you still maintain this project unitl 1.10 is released so we can use it for older Wagtail versions?

**Comment by BertrandBordage** [comment]
Yes!
