### ISSUE TITLE
SQL ProgrammingError in delete_stale_entries with psql 9.2

### ISSUE THREAD

**Issue by jaap3** [leukeleu/wagtail-pg-search-backend#14]
When using Postgres 9.2 the update_index management command fails with:

```
django.db.utils.ProgrammingError: operator does not exist: text = integer
LINE 1: ...agtail_pgsearchbackend_indexentry WHERE object_id IN ((SELEC...
```

This statement is executed by `delete_stale_entries`.

I was able to fix this by changing the SQL to `'DELETE FROM %s WHERE object_id::integer IN (%s);'`, but I feel that this might not be the correct solution.

**Comment by BertrandBordage** [comment]
Right, I forgot that this implicit cast was not handle with previous versions. The explicit cast you wrote, `object_id::integer`, will work on most project, but it will not work when a primary key is not an integer.

I rewrote `delete_stale_entries` in d9d317d319d7e4e3e2bb9f5c86f0216d1b73975a so it’s simpler and uses the ORM only. It should work in your case, could you test it please?

**Comment by jaap3** [comment]
Just checked, the current master seems to work fine, thanks!
