### ISSUE TITLE
broken ranking

### ISSUE THREAD

**Issue by dnsl48** [leukeleu/wagtail-pg-search-backend#15]
Current implementation of `backend.PostgresSearchQuery.search_in_index` implies ordering in a sub-query, performing an inner join of the wagtailcore_page table on the super query level:
https://github.com/wagtail/wagtail-pg-search-backend/blob/1.3.1/wagtail_pgsearchbackend/backend.py#L255

The query looks like that:
```sql
SELECT obj.*
FROM (<<select from ... order by ts_rank>>) AS index_entry
INNER JOIN (<<select from wagtailcore_page>>) AS obj ON obj."%s" = index_entry.typed_pk
OFFSET <<offset>> LIMIT <<limit>>;
```

The problem is that PostgreSQL does not guarantee preserving of the ordering at the outer level.
For example, that happens on my project - the result of the subquery is sorted properly, however the final result seems to be random-ish (depending on the query planner).

Here is somewhat more explanation around it: https://www.postgresql.org/message-id/4CA16EE8.5040406@postnewspapers.com.au

**Comment by BertrandBordage** [comment]
Ah, it’s going to be tough to test, as the query planner may select different algorithms depending on the version and statistics on the table. We can probably force an algorithm to be used by setting PostgreSQL variables, but I doubt this is the right way to test ranking, we should test it in a more general way. I thought Wagtail’s test suite was testing ranking, but it doesn’t appear to be the case… :\
